version: '3'
services:
    drone:
        image: drone/drone:1
        volumes: 
            - ./data/drone:/data
        ports: 
            - 7880:80
            - 7881:443
        environment: 
            - DRONE_GITEA_SERVER=${DRONE_GITEA_SERVER}
            - DRONE_GITEA_CLIENT_ID=${DRONE_GITEA_CLIENT_ID}
            - DRONE_GITEA_CLIENT_SECRET=${DRONE_GITEA_CLIENT_SECRET}
            - DRONE_RPC_SECRET=${DRONE_RPC_SECRET}
            - DRONE_SERVER_HOST=${DRONE_SERVER_HOST}
            - DRONE_SERVER_PROTO=${DRONE_SERVER_PROTO}
            - DRONE_USER_CREATE=${DRONE_USER_CREATE}
        restart: unless-stopped
    drone-runner:
        image: drone/drone-runner-docker:1
        volumes: 
            - /var/run/docker.sock:/var/run/docker.sock
        ports: 
            - 7882:3000
        environment: 
            - DRONE_RPC_HOST=${DRONE_SERVER_HOST}
            - DRONE_RPC_PROTO=${DRONE_SERVER_PROTO}
            - DRONE_RPC_SECRET=${DRONE_RPC_SECRET}
        restart: unless-stopped
