version: "3"
services: 
  v2ray:
    image: v2ray/official
    volumes: 
      - ./config/v2ray.json:/etc/v2ray/config.json
    ports: 
      - ${V2RAY_PORT:-18888}:10086
  mkcp:
    image: v2ray/official
    volumes: 
      - ./config/mkcp.json:/etc/v2ray/config.json
    ports:
      - ${MKCP_PORT:-18887}:10086/udp      