version: '3.7'
services:
    jellyfin:
        image: jellyfin/jellyfin
        volumes: 
            - ./data/jellyfin/config:/config
            - ./data/jellyfin/cache:/cache
            - type: bind
              source: /shared/media
              target: /media
        user: 1000:1000
        network_mode: host
        restart: unless-stopped
